version: '3.8'

services:
  ecommerce-backend:
    build: .
    container_name: ecommerce-backend
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always

networks:
  ecommerce-network:
    driver: bridge
